In [8]:
import pandas as pd

In [4]:
df = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv')

In [5]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [6]:
df.rename(columns={'FTHG':'home goals' , 'FTAG' : 'away goals'} , inplace=True)

In [7]:
df

,Div,Date,Time,HomeTeam,AwayTeam,home goals,away goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

# Read .csv from multiple URL's

In [9]:
"https://football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2122/E0.csv'

In [10]:
root = "https://football-data.co.uk/mmz4281/"

In [35]:
leagues = ['E0','E1','E2','E3','EC']
list=[]
for league in leagues:
   DF = pd.read_csv(root + '2526' + '/' + league + '.csv')
   list.append(DF)

In [37]:
len(list)

5

In [38]:
list[0]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [55]:
leagues = ['E0','E2','E3']
list=[]
for league in leagues:
    for season in range(15, 21):
        dataframe = pd.read_csv(root + str(season)+ str(season+1) + '/' + league + '.csv')
        dataframe.insert(1 , 'season' , season)
        list.append(dataframe)

In [58]:
len(list)

18

In [2]:
list[17]

list[17]

# Organize all data in dictionary

In [3]:
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [4]:
dict_countries['Spanish La Liga']

'SP1'

In [6]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
E0
E2
E3

In [11]:
dict_historical_data = {} 
for league in dict_countries:
    list=[]
    for season in range(15, 21):
        dataframe = pd.read_csv(root + str(season)+ str(season+1) + '/' + dict_countries[league] + '.csv')
        dataframe.insert(1 , 'season' , season)
        list.append(dataframe)
    df_frames = pd.concat(list) # storing all seasons of a league in a single dataframe
    dict_historical_data[league] = df_frames # assigning dataframe to a new dictionary

In [12]:
dict_historical_data

{'Spanish La Liga':      Div  season        Date     HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    SP1      15    21/08/15       Malaga     Sevilla     0     0   D     0
 1    SP1      15    22/08/15   Ath Madrid  Las Palmas     1     0   H     1
 2    SP1      15    22/08/15      Espanol      Getafe     1     0   H     1
 3    SP1      15    22/08/15    La Coruna    Sociedad     0     0   D     0
 4    SP1      15    22/08/15    Vallecano    Valencia     0     0   D     0
 ..   ...     ...         ...          ...         ...   ...   ...  ..   ...
 375  SP1      20  22/05/2021      Osasuna    Sociedad     0     1   A     0
 376  SP1      20  22/05/2021  Real Madrid  Villarreal     2     1   H     0
 377  SP1      20  22/05/2021   Valladolid  Ath Madrid     1     2   A     1
 378  SP1      20  23/05/2021      Granada      Getafe     0     0   D     0
 379  SP1      20  23/05/2021      Sevilla      Alaves     1     0   H     0

      HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
 0       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 1       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 2       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 3       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 4       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 ..    ...  ...      ...   ...       ...       ...    ...    ...      ...
 375     0  ...     2.34  1.00      2.07      1.86   2.06   1.87     2.07
 376     1  ...     2.57 -1.00      2.01      1.92   2.00   1.93     2.02
 377     0  ...     2.30  1.50      1.90      2.03   1.90   2.02     1.95
 378     0  ...     1.80  0.25      1.73      2.08   1.77   2.18     1.84
 379     0  ...     2.40 -1.50      1.97      1.96   1.93   1.99     2.13

      MaxCAHA  AvgCAHH  AvgCAHA
 0        NaN      NaN      NaN
 1        NaN      NaN      NaN
 2        NaN      NaN      NaN
 3        NaN      NaN      NaN
 4        NaN      NaN      NaN
 ..       ...      ...      ...
 375     1.96     1.98     1.88
 376     2.02     1.95     1.92
 377     2.06     1.90     1.97
 378     2.23     1.77     2.12
 379     2.03     1.99     1.88

 [2280 rows x 127 columns],
 'Spanish Segunda Division':      Div  season        Date      HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    SP2      15    22/08/15      Alcorcon    Mallorca     2     0   H   1.0
 1    SP2      15    22/08/15       Cordoba  Valladolid     1     0   H   0.0
 2    SP2      15    22/08/15        Huesca      Alaves     2     3   A   0.0
 3    SP2      15    22/08/15    Llagostera     Osasuna     0     2   A   0.0
 4    SP2      15    23/08/15       Almeria     Leganes     3     2   H   3.0
 ..   ...     ...         ...           ...         ...   ...   ...  ..   ...
 457  SP2      20  30/05/2021      Mirandes    Sabadell     0     2   A   0.0
 458  SP2      20  30/05/2021  Ponferradina    Mallorca     2     2   D   1.0
 459  SP2      20  30/05/2021      Sp Gijon     Almeria     0     2   A   0.0
 460  SP2      20  30/05/2021     Vallecano        Lugo     0     1   A   0.0
 461  SP2      20  30/05/2021      Zaragoza     Leganes     0     5   A   0.0

      HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
 0     0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 1     0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 2     1.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 3     0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 4     0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 ..    ...  ...      ...   ...       ...       ...    ...    ...      ...
 457   0.0  ...     1.74  0.50      2.02      1.83   2.05   1.86     2.06
 458   1.0  ...     1.83  0.25      2.00      1.85   2.02   1.89     2.04
 459   0.0  ...     1.83 -0.75      1.80      2.05   1.84   2.08     1.89
 460   1.0  ...     1.87 -1.00      1.95      1.90   1.97   1.93     2.02
 461   3.0  ...     1.64  0.50      1.83      2.02   1.85   2.07     1.87

      MaxCAHA  AvgCAHH  AvgCAHA
 0        NaN      NaN      NaN
 1        NaN      NaN      NaN
 2        NaN      NaN      NaN
 3        NaN      NaN      NaN
 4        NaN      NaN      NaN
 ..       ...      ...      ...
 457     1.89     2.00     1.83
 458     1.92     1.99     1.85
 459     2.08     1.83     2.02
 460     1.94     1.96     1.88
 461     2.08     1.80     2.04

 [2772 rows x 127 columns],
 'German Bundesliga':     Div  season        Date       HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    D1      15    14/08/15  Bayern Munich     Hamburg     5     0   H     1
 1    D1      15    15/08/15       Augsburg      Hertha     0     1   A     0
 2    D1      15    15/08/15      Darmstadt    Hannover     2     2   D     1
 3    D1      15    15/08/15       Dortmund  M'gladbach     4     0   H     3
 4    D1      15    15/08/15     Leverkusen  Hoffenheim     2     1   H     1
 ..   ..     ...         ...            ...         ...   ...   ...  ..   ...
 301  D1      20  22/05/2021     Hoffenheim      Hertha     2     1   H     0
 302  D1      20  22/05/2021      Stuttgart   Bielefeld     0     2   A     0
 303  D1      20  22/05/2021   Union Berlin  RB Leipzig     2     1   H     0
 304  D1      20  22/05/2021  Werder Bremen  M'gladbach     2     4   A     0
 305  D1      20  22/05/2021      Wolfsburg       Mainz     2     3   A     0

      HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
 0       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 1       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 2       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 3       0  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 4       1  ...      NaN   NaN       NaN       NaN    NaN    NaN      NaN
 ..    ...  ...      ...   ...       ...       ...    ...    ...      ...
 301     1  ...     2.96 -0.75      1.86      2.07   1.88   2.06     1.99
 302     0  ...     2.50 -0.25      2.03      1.90   2.02   1.90     2.06
 303     0  ...     2.34  0.50      1.97      1.96   1.97   1.95     1.98
 304     1  ...     2.52  0.25      2.04      1.89   2.03   1.90     2.07
 305     1  ...     2.97 -0.75      2.05      1.75   2.09   1.83     2.13

      MaxCAHA  AvgCAHH  AvgCAHA
 0        NaN      NaN      NaN
 1        NaN      NaN      NaN
 2        NaN      NaN      NaN
 3        NaN      NaN      NaN
 4        NaN      NaN      NaN
 ..       ...      ...      ...
 301     2.08     1.88     2.00
 302     1.91     2.01     1.87
 303     1.98     1.92     1.95
 304     1.91     2.00     1.87
 305     1.89     2.04     1.83

 [1836 rows x 127 columns],
 'English Premier League':     Div  season        Date          HomeTeam        AwayTeam  FTHG  FTAG FTR  \
 0    E0      15  08/08/2015       Bournemouth     Aston Villa     0     1   A
 1    E0      15  08/08/2015           Chelsea         Swansea     2     2   D
 2    E0      15  08/08/2015           Everton         Watford     2     2   D
 3    E0      15  08/08/2015         Leicester      Sunderland     4     2   H
 4    E0      15  08/08/2015        Man United       Tottenham     1     0   H
 ..   ..     ...         ...               ...             ...   ...   ...  ..
 375  E0      20  23/05/2021         Liverpool  Crystal Palace     2     0   H
 376  E0      20  23/05/2021          Man City         Everton     5     0   H
 377  E0      20  23/05/2021  Sheffield United         Burnley     1     0   H
 378  E0      20  23/05/2021          West Ham     Southampton     3     0   H
 379  E0      20  23/05/2021            Wolves      Man United     1     2   A

      HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       0     0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 1       2     1  ...      NaN   NaN       NaN       NaN    NaN    NaN
 2       0     1  ...      NaN   NaN       NaN       NaN    NaN    NaN
 3       3     0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 4       1     0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 ..    ...   ...  ...      ...   ...       ...       ...    ...    ...
 375     1     0  ...     3.49 -2.25      1.86      2.04   1.88   2.03
 376     2     0  ...     2.77 -1.75      2.01      1.89   1.99   1.89
 377     1     0  ...     2.05  0.00      2.04      1.86   2.05   1.86
 378     2     0  ...     2.14 -0.75      2.00      1.90   2.02   1.91
 379     1     2  ...     1.62 -0.25      2.04      1.86   2.10   1.84

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0        NaN      NaN      NaN      NaN
 1        NaN      NaN      NaN      NaN
 2        NaN      NaN      NaN      NaN
 3        NaN      NaN      NaN      NaN
 4        NaN      NaN      NaN      NaN
 ..       ...      ...      ...      ...
 375     1.98     2.14     1.88     2.00
 376     2.20     2.00     2.03     1.85
 377     2.17     1.90     2.03     1.84
 378     2.06     2.01     1.99     1.89
 379     2.10     1.94     2.00     1.88

 [2280 rows x 128 columns],
 'English League 1':     Div  season        Date            HomeTeam     AwayTeam  FTHG  FTAG FTR  \
 0    E2      15    08/08/15              Burton   Scunthorpe   2.0   1.0   H
 1    E2      15    08/08/15        Chesterfield     Barnsley   3.0   1.0   H
 2    E2      15    08/08/15          Colchester    Blackpool   2.0   2.0   D
 3    E2      15    08/08/15            Coventry        Wigan   2.0   0.0   H
 4    E2      15    08/08/15               Crewe    Port Vale   0.0   0.0   D
 ..   ..     ...         ...                 ...          ...   ...   ...  ..
 547  E2      20  09/05/2021  Milton Keynes Dons     Rochdale   0.0   3.0   A
 548  E2      20  09/05/2021              Oxford       Burton   4.0   0.0   H
 549  E2      20  09/05/2021          Portsmouth   Accrington   0.0   1.0   A
 550  E2      20  09/05/2021          Sunderland  Northampton   1.0   1.0   D
 551  E2      20  09/05/2021               Wigan      Swindon   3.0   4.0   A

      HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0     0.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 1     0.0   1.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 2     1.0   2.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 3     1.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 4     0.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 ..    ...   ...  ...      ...   ...       ...       ...    ...    ...
 547   0.0   0.0  ...     2.56 -0.75      1.88      1.98   1.88   2.01
 548   2.0   0.0  ...     2.38 -1.00      1.85      2.00   1.88   2.02
 549   0.0   1.0  ...     2.21 -1.00      1.95      1.90   1.99   1.90
 550   0.0   0.0  ...     2.13 -1.25      1.98      1.88   2.02   1.88
 551   1.0   0.0  ...     2.28 -0.75      1.93      1.93   2.00   1.88

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0        NaN      NaN      NaN      NaN
 1        NaN      NaN      NaN      NaN
 2        NaN      NaN      NaN      NaN
 3        NaN      NaN      NaN      NaN
 4        NaN      NaN      NaN      NaN
 ..       ...      ...      ...      ...
 547     1.96     2.04     1.87     1.97
 548     2.11     2.06     1.88     1.95
 549     2.07     1.94     1.95     1.88
 550     2.10     1.91     2.01     1.83
 551     2.01     1.97     1.93     1.90

 [3161 rows x 128 columns],
 'English League 2':     Div  season        Date       HomeTeam        AwayTeam  FTHG  FTAG FTR  \
 0    E3      15    08/08/15     Accrington           Luton   1.0   1.0   D
 1    E3      15    08/08/15  AFC Wimbledon        Plymouth   0.0   2.0   A
 2    E3      15    08/08/15    Bristol Rvs     Northampton   0.0   1.0   A
 3    E3      15    08/08/15      Cambridge  Newport County   3.0   0.0   H
 4    E3      15    08/08/15         Exeter          Yeovil   3.0   2.0   H
 ..   ..     ...         ...            ...             ...   ...   ...  ..
 547  E3      20  08/05/2021      Port Vale       Mansfield   0.0   3.0   A
 548  E3      20  08/05/2021     Scunthorpe       Stevenage   0.0   1.0   A
 549  E3      20  08/05/2021       Southend  Newport County   1.0   1.0   D
 550  E3      20  08/05/2021       Tranmere      Colchester   0.0   0.0   D
 551  E3      20  08/05/2021        Salford   Leyton Orient   3.0   0.0   H

      HTHG  HTAG  ... AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0     0.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 1     0.0   1.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 2     0.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 3     1.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 4     2.0   0.0  ...      NaN   NaN       NaN       NaN    NaN    NaN
 ..    ...   ...  ...      ...   ...       ...       ...    ...    ...
 547   0.0   2.0  ...     1.84  0.25      1.90      1.95   1.89   2.00
 548   0.0   0.0  ...     1.73  0.50      1.80      2.05   1.84   2.06
 549   1.0   0.0  ...     1.44  0.50      1.93      1.93   1.94   1.94
 550   0.0   0.0  ...     1.59 -0.75      2.05      1.80   2.05   1.85
 551   1.0   0.0  ...     1.87 -1.00      1.98      1.88   1.99   1.90

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0        NaN      NaN      NaN      NaN
 1        NaN      NaN      NaN      NaN
 2        NaN      NaN      NaN      NaN
 3        NaN      NaN      NaN      NaN
 4        NaN      NaN      NaN      NaN
 ..       ...      ...      ...      ...
 547     1.95     2.07     1.85     1.97
 548     1.87     2.14     1.77     2.07
 549     1.97     1.97     1.91     1.91
 550     2.08     1.89     2.01     1.82
 551     2.01     1.96     1.96     1.86

 [3201 rows x 128 columns]}

In [13]:
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'English Premier League', 'English League 1', 'English League 2'])

In [15]:
dict_historical_data['Spanish La Liga']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,15,21/08/15,Malaga,Sevilla,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,15,22/08/15,Ath Madrid,Las Palmas,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,15,22/08/15,Espanol,Getafe,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,15,22/08/15,La Coruna,Sociedad,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,15,22/08/15,Vallecano,Valencia,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,20,22/05/2021,Osasuna,Sociedad,0,1,A,0,0,...,2.34,1.00,2.07,1.86,2.06,1.87,2.07,1.96,1.98,1.88
376,SP1,20,22/05/2021,Real Madrid,Villarreal,2,1,H,0,1,...,2.57,-1.00,2.01,1.92,2.00,1.93,2.02,2.02,1.95,1.92
377,SP1,20,22/05/2021,Valladolid,Ath Madrid,1,2,A,1,0,...,2.30,1.50,1.90,2.03,1.90,2.02,1.95,2.06,1.90,1.97
378,SP1,20,23/05/2021,Granada,Getafe,0,0,D,0,0,...,1.80,0.25,1.73,2.08,1.77,2.18,1.84,2.23,1.77,2.12
379,SP1,20,23/05/2021,Sevilla,Alaves,1,0,H,0,0,...,2.40,-1.50,1.97,1.96,1.93,1.99,2.13,2.03,1.99,1.88