# With Arrays 1.Numpy

In [12]:
import pandas as pd
import numpy as np
data = np.array([ # create an array
    [1,4],
    [2,5],
    [3,6]
])

In [13]:
# creating dataframe
df = pd.DataFrame(data , index = ['r1','r2','r3'] , columns = ['c1','c2'])

In [14]:
df

    c1  c2
r1   1   4
r2   2   5
r3   3   6

# With Arrays 1.List

In [15]:
list = [[1,4],
    [2,5],
    [3,6]]
list

[[1, 4], [2, 5], [3, 6]]

In [16]:
df = pd.DataFrame(data , index = ['r1','r2','r3'] , columns = ['c1','c2'])
df

    c1  c2
r1   1   4
r2   2   5
r3   3   6

# Using Dictionary

In [17]:
countries = ["india","USA","China","Brazil","England"]
pops = [1500000000,347275807,1700000000,110000000,10000000]

In [18]:
dict = {'Countries' : countries , 'Population' : pops}
dict

{'Countries': ['india', 'USA', 'China', 'Brazil', 'England'],
 'Population': [1500000000, 347275807, 1700000000, 110000000, 10000000]}

In [19]:
df = pd.DataFrame(dict)
df

  Countries  Population
0     india  1500000000
1       USA   347275807
2     China  1700000000
3    Brazil   110000000
4   England    10000000

# From CSV FILE

In [ ]:
# pd.read_csv("filename.csv")